sudo: false

language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
env:
  - DJANGO="master"
  - DJANGO="30"
  - DJANGO="22"
  - DJANGO="21"
  - DJANGO="21"
  - DJANGO="20"
  - DJANGO="111"

install:
  - pip install tox

script:
  - tox -e py$(python -c 'import sys;print("".join(map(str, sys.version_info[:2])))')-django${DJANGO}

jobs:
  fast_finish: true
  allow_failures:
    - env: DJANGO="master"
  exclude:
    - python: "3.5"
      env: DJANGO="30"
    - python: "3.5"
      env: DJANGO="master"

notifications:
  irc: "irc.freenode.org#imagekit"
